#!/usr/bin/env sh
set -eu

STACK_FILE="${STACK_FILE:-deploy/hive-stack.yml}"
HIVE_DIRECT_PORT="${HIVE_DIRECT_PORT:-8080}"
HIVE_CONTROL_PLANE_PORT="${HIVE_CONTROL_PLANE_PORT:-3000}"
HIVE_HEALTH_HOST="${HIVE_HEALTH_HOST:-}"
# Wildcard certificates (DNS-01): set HIVE_ACME_DNS_PROVIDER (e.g. cloudflare)
# and HIVE_ACME_DNS_TOKEN to switch Traefik's Let's Encrypt solver to the
# DNS-01 challenge, which is required for wildcard domains (*.example.com).
# The token is stored as the swarm secret 'hive-acme-dns-token' and a generated
# compose overlay merges the DNS-01 flags into the traefik service. When
# HIVE_ACME_DNS_PROVIDER is unset nothing changes (TLS-ALPN-01 as before).
ACME_DNS_OVERLAY=""

ensure_acme_dns_overlay() {
  [ -n "$ACME_DNS_OVERLAY" ] && return 0
  if [ -z "${HIVE_ACME_DNS_PROVIDER:-}" ]; then
    return 0
  fi
  if [ -z "${HIVE_ACME_DNS_TOKEN:-}" ]; then
    echo "HIVE_ACME_DNS_TOKEN is required when HIVE_ACME_DNS_PROVIDER is set" >&2
    exit 1
  fi

  # Create or refresh the provider token secret. A secret in use by a running
  # service cannot be removed; keep the existing token in that case.
  if docker secret ls --format '{{.Name}}' | grep -qx 'hive-acme-dns-token'; then
    if docker secret rm hive-acme-dns-token >/dev/null 2>&1; then
      printf '%s' "$HIVE_ACME_DNS_TOKEN" | docker secret create hive-acme-dns-token - >/dev/null
      echo "Updated secret: hive-acme-dns-token"
    else
      echo "Secret hive-acme-dns-token is in use; keeping the existing token" >&2
    fi
  else
    printf '%s' "$HIVE_ACME_DNS_TOKEN" | docker secret create hive-acme-dns-token - >/dev/null
    echo "Created secret: hive-acme-dns-token"
  fi

  ACME_DNS_OVERLAY="$(mktemp "${TMPDIR:-/tmp}/hive-acme-dns.XXXXXX")"
  cat >"$ACME_DNS_OVERLAY" <<EOF
# Generated by deploy/init.sh: DNS-01 challenge overlay for wildcard certs.
# Compose replaces command lists when merging, so this repeats the base
# traefik command from deploy/hive-stack.yml and appends the DNS-01 flags.
version: "3.9"

services:
  traefik:
    command:
      - --providers.swarm=true
      - --providers.swarm.exposedByDefault=false
      - --providers.swarm.network=hive_proxy
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --certificatesresolvers.letsencrypt.acme.email=\${ACME_EMAIL:-admin@example.invalid}
      - --certificatesresolvers.letsencrypt.acme.storage=/data/shared/acme.json
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=${HIVE_ACME_DNS_PROVIDER}
    environment:
      # Cloudflare reads its API token from CF_DNS_API_TOKEN_FILE. Other
      # providers need their own variables here instead (e.g.
      # AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY for route53) — see the lego
      # DNS provider reference for the exact names.
      - CF_DNS_API_TOKEN_FILE=/run/secrets/acme-dns-token
    secrets:
      - source: acme-dns-token
        target: /run/secrets/acme-dns-token
secrets:
  acme-dns-token:
    external: true
EOF
  trap 'rm -f "$ACME_DNS_OVERLAY"' EXIT
  echo "DNS-01 overlay ready (${HIVE_ACME_DNS_PROVIDER})"
}

detect_host_ip() {
  ip="$(docker info --format '{{.Swarm.NodeAddr}}' 2>/dev/null || true)"
  if [ -n "$ip" ] && [ "$ip" != "0.0.0.0" ] && [ "$ip" != "<no value>" ]; then
    case "$ip" in
      127.*|169.254.*|172.17.*|172.18.*|172.19.*|172.20.*|172.21.*|172.22.*|172.23.*|172.24.*|172.25.*|172.26.*|172.27.*|172.28.*|172.29.*|172.30.*|172.31.*)
        : ;;
      *)
        echo "$ip"
        return
        ;;
    esac
  fi

  ip="$(ip route get 1.1.1.1 2>/dev/null | awk '{for (i=1; i<=NF; i++) if ($i == "src") {print $(i+1); exit}}' || true)"
  if [ -n "$ip" ]; then
    echo "$ip"
    return
  fi

  for ip in $(hostname -I 2>/dev/null || true); do
    case "$ip" in
      127.*|169.254.*|172.17.*|172.18.*|172.19.*|172.20.*|172.21.*|172.22.*|172.23.*|172.24.*|172.25.*|172.26.*|172.27.*|172.28.*|172.29.*|172.30.*|172.31.*)
        :
        ;;
      *)
        echo "$ip"
        return
        ;;
    esac
  done

  echo "localhost"
}

check_health() {
  url="$1"
  if command -v curl >/dev/null 2>&1; then
    curl -sf -m 3 "$url" | grep -q '"status":"ok"'
    return $?
  fi
  if command -v wget >/dev/null 2>&1; then
    wget -q -O - "$url" 2>/dev/null | grep -q '"status":"ok"'
    return $?
  fi
  return 1
}
print_swarm_join_commands() {
  mgr_token="$(docker swarm join-token manager -q 2>/dev/null || true)"
  worker_token="$(docker swarm join-token worker -q 2>/dev/null || true)"
  if [ -z "$mgr_token" ] && [ -z "$worker_token" ]; then
    return 0
  fi
  node_addr="$(docker info --format '{{.Swarm.NodeAddr}}' 2>/dev/null || true)"
  echo "Join additional nodes to this swarm:"
  if [ -n "$mgr_token" ]; then
    echo "  Manager: docker swarm join --token ${mgr_token} ${node_addr:-<manager-ip>}:2377"
  fi
  if [ -n "$worker_token" ]; then
    echo "  Worker:  docker swarm join --token ${worker_token} ${node_addr:-<manager-ip>}:2377"
  fi
}

path_contains_dir() {
  dir="$1"
  old_ifs="$IFS"
  IFS=:
  for part in ${PATH:-}; do
    if [ "$part" = "$dir" ]; then
      IFS="$old_ifs"
      return 0
    fi
  done
  IFS="$old_ifs"
  return 1
}

install_hivectl_cli() {
  case "${HIVE_INSTALL_CLI:-true}" in
    false|False|FALSE|0|no|NO)
      echo "Skipping hivectl CLI install because HIVE_INSTALL_CLI=${HIVE_INSTALL_CLI}"
      return 0
      ;;
  esac

  script_dir="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
  src="$(CDPATH= cd -- "$script_dir/.." && pwd)/hivectl"
  if [ ! -f "$src" ]; then
    echo "Warning: $src not found; skipping hivectl CLI install"
    return 0
  fi

  target="${HIVE_CLI_PATH:-/usr/local/bin/hivectl}"
  target_dir="$(dirname -- "$target")"
  if mkdir -p "$target_dir" 2>/dev/null && install -m 0755 "$src" "$target" 2>/dev/null; then
    echo "Installed hivectl CLI: $target"
    return 0
  fi
  if command -v sudo >/dev/null 2>&1 && sudo -n true >/dev/null 2>&1; then
    if sudo mkdir -p "$target_dir" && sudo install -m 0755 "$src" "$target"; then
      echo "Installed hivectl CLI: $target"
      return 0
    fi
  fi
  if [ -n "${HOME:-}" ]; then
    fallback="$HOME/.local/bin/hivectl"
    fallback_dir="$(dirname -- "$fallback")"
    if mkdir -p "$fallback_dir" && install -m 0755 "$src" "$fallback"; then
      echo "Installed hivectl CLI: $fallback"
      if ! path_contains_dir "$fallback_dir"; then
        echo "Warning: $fallback_dir is not in PATH. Add: export PATH=\"$fallback_dir:\$PATH\""
      fi
      return 0
    fi
  fi
  echo "Warning: could not install hivectl CLI. Set HIVE_CLI_PATH to a writable path and rerun."
}

release_legacy_traefik_direct_port() {
  svc="hive_traefik"
  if ! docker service inspect "$svc" >/dev/null 2>&1; then
    return 0
  fi

  ports="$(docker service inspect --format '{{range .Endpoint.Spec.Ports}}{{printf "%d:%d/%s\n" .PublishedPort .TargetPort .Protocol}}{{end}}' "$svc" 2>/dev/null || true)"
  if ! printf '%s\n' "$ports" | grep -qx "${HIVE_DIRECT_PORT}:8080/tcp"; then
    return 0
  fi

  echo "Repairing previous Traefik direct-port binding on :${HIVE_DIRECT_PORT}"
  if docker service update --publish-rm 8080 "$svc" >/dev/null; then
    i=0
    while [ "$i" -lt 30 ]; do
      ports="$(docker service inspect --format '{{range .Endpoint.Spec.Ports}}{{printf "%d:%d/%s\n" .PublishedPort .TargetPort .Protocol}}{{end}}' "$svc" 2>/dev/null || true)"
      if ! printf '%s\n' "$ports" | grep -qx "${HIVE_DIRECT_PORT}:8080/tcp"; then
        echo "Previous Traefik direct port released"
        return 0
      fi
      sleep 2
      i=$((i + 2))
    done
  fi

  echo "Warning: Traefik still owns :${HIVE_DIRECT_PORT}; removing ${svc} so stack deploy can recreate it cleanly"
  docker service rm "$svc" >/dev/null 2>&1 || true
  i=0
  while [ "$i" -lt 30 ]; do
    if ! docker service inspect "$svc" >/dev/null 2>&1; then
      echo "Removed stale Traefik service"
      return 0
    fi
    sleep 2
    i=$((i + 2))
  done

  echo "Warning: stale Traefik service still exists; deploy may report a port conflict"
}

install_hivectl_cli

echo "Checking swarm status..."
if ! docker info --format '{{.Swarm.LocalNodeState}}' | grep -q active; then
  echo "Swarm inactive, running docker swarm init"
  docker swarm init
fi

if [ -z "${HIVE_DOMAIN:-}" ]; then
  echo "HIVE_DOMAIN is not set; Hive will be available on the direct HTTP port only."
  ACME_EMAIL="${ACME_EMAIL:-admin@example.invalid}"
  HIVE_TRAEFIK_ENABLE="${HIVE_TRAEFIK_ENABLE:-false}"
  export ACME_EMAIL HIVE_TRAEFIK_ENABLE
elif [ -z "${ACME_EMAIL:-}" ]; then
  echo "ACME_EMAIL is required when HIVE_DOMAIN is set"
  exit 1
else
  HIVE_TRAEFIK_ENABLE="${HIVE_TRAEFIK_ENABLE:-true}"
  export HIVE_TRAEFIK_ENABLE
fi

create_secret() {
  name="$1"
  if ! docker secret ls --format '{{.Name}}' | grep -q "^${name}$"; then
    value="$(openssl rand -hex 32)"
    printf "%s" "$value" | docker secret create "$name" -
  fi
}

create_secret hive-master-key
create_secret postgres-password
create_secret hive-jwt-secret
create_secret agent-bootstrap-token

# The stack references these overlay networks as external so their names stay
# stable regardless of the stack name (Traefik and database provisioning
# reference them by exact name).
if ! docker network ls --format '{{.Name}}' | grep -q '^hive_internal$'; then
  docker network create --driver overlay --attachable --opt encrypted=true hive_internal
fi
if ! docker network ls --format '{{.Name}}' | grep -q '^hive_proxy$'; then
  docker network create --driver overlay --attachable hive_proxy
fi

node_has_label() {
  docker node inspect --format "{{ index .Spec.Labels \"$2\" }}" "$1" 2>/dev/null | grep -qx true
}

first_node_with_label() {
  label="$1"
  for node in $(docker node ls --format '{{.Hostname}}'); do
    if node_has_label "$node" "$label"; then
      echo "$node"
      return 0
    fi
  done
  return 1
}

running_service_node() {
  docker service ps "hive_$1" --filter desired-state=running --format '{{.Node}}' 2>/dev/null | head -n 1
}

ensure_singleton_node_label() {
  label="$1"
  service="$2"
  purpose="$3"
  target="$(running_service_node "$service" || true)"
  if [ -z "$target" ]; then
    target="$(first_node_with_label "$label" || true)"
  fi
  if [ -z "$target" ]; then
    target="$(docker node ls --format '{{.Hostname}}' | head -n 1)"
  fi
  for node in $(docker node ls --format '{{.Hostname}}'); do
    if [ "$node" = "$target" ]; then
      docker node update --label-add "${label}=true" "$node" >/dev/null 2>&1 || true
    elif node_has_label "$node" "$label"; then
      docker node update --label-rm "$label" "$node" >/dev/null 2>&1 || true
    fi
  done
  echo "$purpose pinned to node: $target"
}

# Swarm named volumes are node-local by default. Preserve the current stateful
# service node across re-installs/updates so Postgres/registry do not appear
# empty after being rescheduled to a different node.
ensure_singleton_node_label db postgres "Postgres data"
ensure_singleton_node_label registry registry "Registry data"
builder_node="$(running_service_node buildkit || true)"
if [ -z "$builder_node" ]; then
  builder_node="$(first_node_with_label builder || true)"
fi
if [ -z "$builder_node" ]; then
  builder_node="$(docker node ls --format '{{.Hostname}}' | head -n 1)"
fi
docker node update --label-add builder=true "$builder_node" >/dev/null 2>&1 || true

release_legacy_traefik_direct_port

# BuildKit cannot run as a swarm service (services lack CAP_SYS_ADMIN, and
# buildkitd's snapshotter needs mount(2)). Run it as a privileged host-level
# container on this builder node; the control plane reaches it via the
# 'buildkit' network alias on hive_internal.
ensure_buildkit() {
  if docker ps --format '{{.Names}}' | grep -qx 'hive-buildkit'; then
    return 0
  fi
  # buildkitd.toml: allow the plain-HTTP internal registry.
  mkdir -p /etc/hive
  printf '[registry."registry:5000"]\n  http = true\n  insecure = true\n' > /etc/hive/buildkitd.toml
  docker rm -f hive-buildkit >/dev/null 2>&1 || true
  docker run -d --privileged --restart=unless-stopped \
    --name hive-buildkit \
    --network hive_internal --network-alias buildkit \
    -v /etc/hive/buildkitd.toml:/etc/buildkit/buildkitd.toml:ro \
    -v hive_buildkit-cache:/var/lib/buildkit \
    moby/buildkit:latest --addr tcp://0.0.0.0:1234 >/dev/null
}

ensure_buildkit

ensure_acme_dns_overlay

echo "Deploying stack (image tag: ${HIVE_IMAGE_TAG:-latest})..."
if [ -n "$ACME_DNS_OVERLAY" ]; then
  docker stack deploy -c "$STACK_FILE" -c "$ACME_DNS_OVERLAY" hive
else
  docker stack deploy -c "$STACK_FILE" hive
fi

echo "Waiting for API health..."
health_host="${HIVE_HEALTH_HOST:-$(detect_host_ip)}"
healthy=false
direct_misroute=false
for i in $(seq 1 60); do
  if check_health "http://${health_host}:${HIVE_DIRECT_PORT}/api/v1/health"; then
    echo "Hive direct health endpoint is healthy"
    healthy=true
    break
  fi
  if wget -q -O - "http://${health_host}:${HIVE_DIRECT_PORT}/api/v1/health" >/dev/null 2>&1; then
    direct_misroute=true
  fi
  if check_health "http://${health_host}:${HIVE_CONTROL_PLANE_PORT}/api/v1/health"; then
    echo "Hive control-plane is healthy"
    healthy=true
    break
  fi
  sleep 2
done

if [ "$healthy" != "true" ]; then
  echo "Hive did not become healthy. Docker service diagnostics:"
  if [ "$direct_misroute" = "true" ]; then
    echo "  Direct port (${HIVE_DIRECT_PORT}) appears reachable but returned non-health response (possible routing/port collision)."
  fi
  docker service ls --filter label=com.docker.stack.namespace=hive || true
  docker service ps --no-trunc hive_control-plane || true
  docker service ps --no-trunc hive_traefik || true
  exit 1
fi

host_ip="${health_host:-$(detect_host_ip)}"
echo "Done. Direct UI: http://${host_ip}:${HIVE_DIRECT_PORT}"
echo "Cloudflare Tunnel target: http://localhost:${HIVE_DIRECT_PORT}"
if [ -n "${HIVE_DOMAIN:-}" ]; then
  echo "Domain URL: https://${HIVE_DOMAIN}"
fi
print_swarm_join_commands
