-- Down migration: drops all app-domain tables.
-- WARNING: This is destructive and should only be used in development.

DROP TABLE IF EXISTS ceph_pool CASCADE;
DROP TABLE IF EXISTS ceph_osd CASCADE;
DROP TABLE IF EXISTS ceph_cluster CASCADE;
DROP TABLE IF EXISTS custom_template CASCADE;
DROP TABLE IF EXISTS template_source CASCADE;
DROP TABLE IF EXISTS log_forward_config CASCADE;
DROP TABLE IF EXISTS log_entry CASCADE;
DROP TABLE IF EXISTS app_env_var CASCADE;
DROP TABLE IF EXISTS maintenance_run CASCADE;
DROP TABLE IF EXISTS maintenance_task CASCADE;
DROP TABLE IF EXISTS service_link CASCADE;
DROP TABLE IF EXISTS preview_deployment CASCADE;
DROP TABLE IF EXISTS dns_record CASCADE;
DROP TABLE IF EXISTS dns_provider CASCADE;
DROP TABLE IF EXISTS node_metrics_snapshot CASCADE;
DROP TABLE IF EXISTS alert_threshold CASCADE;
DROP TABLE IF EXISTS stack CASCADE;
DROP TABLE IF EXISTS custom_certificate CASCADE;
DROP TABLE IF EXISTS proxy_route CASCADE;
DROP TABLE IF EXISTS app_volume CASCADE;
DROP TABLE IF EXISTS app_secret CASCADE;
DROP TABLE IF EXISTS volume CASCADE;
DROP TABLE IF EXISTS secret CASCADE;
DROP TABLE IF EXISTS notification_event CASCADE;
DROP TABLE IF EXISTS notification_channel CASCADE;
DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS backup_run CASCADE;
DROP TABLE IF EXISTS backup_config CASCADE;
DROP TABLE IF EXISTS git_source CASCADE;
DROP TABLE IF EXISTS domain CASCADE;
DROP TABLE IF EXISTS managed_database CASCADE;
DROP TABLE IF EXISTS deployment CASCADE;
DROP TABLE IF EXISTS app CASCADE;
DROP TABLE IF EXISTS project CASCADE;
DROP TABLE IF EXISTS storage_host CASCADE;
