kind: Template
name: bugsink
description: Bugsink is a self-hosted Error Tracker. Built to self-host; Sentry-SDK compatible; Scalable and reliable
category: hosting
tags:
    - hosting
    - self-hosted
    - development
icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/bugsink.svg
version: latest
links:
    docs: https://www.bugsink.com/docs/
    github: https://github.com/bugsink/bugsink/
    website: https://www.bugsink.com/
image: postgres:17-alpine
stack: true
services:
    - name: db
      image: postgres:17-alpine
      env:
        POSTGRES_DB: ""
        POSTGRES_PASSWORD: ""
        POSTGRES_USER: ""
      volumes:
        - db-data:/var/lib/postgresql/data
    - name: web
      image: bugsink/bugsink:latest
      env:
        BASE_URL: ""
        BEHIND_HTTPS_PROXY: ""
        CREATE_SUPERUSER: ""
        DATABASE_URL: postgresql://:@db:5432/
        PORT: "8000"
        SECRET_KEY: ""
