kind: Template
name: bytebase
description: Bytebase is a database management tool that allows you to manage your databases with ease. It provides a simple and effective solution for managing your databases from anywhere.
category: databases
tags:
    - database
    - self-hosted
icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/bytebase.svg
version: latest
links:
    docs: https://www.bytebase.com/docs
    github: https://github.com/bytebase/bytebase
    website: https://www.bytebase.com
image: bytebase/bytebase:3.3.0
ports:
    - "8080"
stack: true
services:
    - name: bytebase
      image: bytebase/bytebase:3.3.0
      ports:
        - "8080"
      env:
        PG_URL: postgres://postgres:@bytebase-db:5432/bytebase
      volumes:
        - data:/var/opt/bytebase
    - name: bytebase-db
      image: postgres:13
      env:
        POSTGRES_DB: bytebase
        POSTGRES_PASSWORD: ""
        POSTGRES_USER: postgres
      volumes:
        - db_data:/var/lib/postgresql/data
