kind: Template
name: chiefonboarding
description: Chief-Onboarding is a comprehensive, self-hosted onboarding and employee management platform designed for businesses to streamline their onboarding processes.
category: employee onboarding
tags:
    - Employee Onboarding
    - HR Management
    - Task Tracking
    - Role-Based Access
    - Document Management
icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/chief-onboarding.svg
version: v2.2.5
links:
    docs: https://docs.chiefonboarding.com/
    github: https://github.com/chiefonboarding/chiefonboarding
    website: https://demo.chiefonboarding.com/
image: chiefonboarding/chiefonboarding:v2.2.5
ports:
    - "8000"
stack: true
services:
    - name: chiefonboarding
      image: chiefonboarding/chiefonboarding:v2.2.5
      ports:
        - "8000"
      env:
        ALLOWED_HOSTS: ""
        DATABASE_URL: postgres://postgres:@db:5432/chiefonboarding
        SECRET_KEY: ""
    - name: db
      image: postgres:13
      env:
        POSTGRES_DB: chiefonboarding
        POSTGRES_PASSWORD: ""
      volumes:
        - postgres_data:/var/lib/postgresql/data
