kind: Template
name: easyappointments
description: Easy!Appointments is a highly customizable web application that allows customers to book appointments with you via a sophisticated web interface.
category: scheduling
tags:
    - scheduling
    - appointments
    - booking
icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/easy!appointments.svg
version: 1.5.0
links:
    docs: https://easyappointments.org/docs
    github: https://github.com/alextselegidis/easyappointments
    website: https://easyappointments.org
image: alextselegidis/easyappointments:1.5.0
stack: true
services:
    - name: easyappointments
      image: alextselegidis/easyappointments:1.5.0
      env:
        BASE_URL: http://
        DB_HOST: mysql
        DB_NAME: easyappointments
        DB_PASSWORD: ""
        DB_USERNAME: root
      volumes:
        - easyappointments:/var/www/html
    - name: mysql
      image: mysql:8.0
      env:
        MYSQL_DATABASE: easyappointments
        MYSQL_ROOT_PASSWORD: ""
      volumes:
        - mysql:/var/lib/mysql
