kind: Template
name: linkwarden
description: Self-hosted, open-source collaborative bookmark manager to collect, organize and archive webpages.
category: productivity
tags:
    - bookmarks
    - link-sharing
icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/linkwarden.svg
version: 2.9.3
links:
    docs: https://docs.linkwarden.app/
    github: https://github.com/linkwarden/linkwarden
    website: https://linkwarden.app/
image: ghcr.io/linkwarden/linkwarden:v2.9.3
ports:
    - "3000"
stack: true
services:
    - name: linkwarden
      image: ghcr.io/linkwarden/linkwarden:v2.9.3
      ports:
        - "3000"
      env:
        DATABASE_URL: postgresql://linkwarden:@postgres:5432/linkwarden
      volumes:
        - linkwarden-data:/data/data
    - name: postgres
      image: postgres:17-alpine
      env:
        POSTGRES_DB: linkwarden
        POSTGRES_PASSWORD: ""
        POSTGRES_USER: linkwarden
      volumes:
        - postgres-data:/var/lib/postgresql/data
