kind: Template
name: nextcloud-aio
description: Nextcloud is a self-hosted file storage and sync platform with powerful collaboration capabilities. It integrates Files, Talk, Groupware, Office, Assistant and more into a single platform for remote work and data protection.
category: file-manager
tags:
    - file-manager
    - sync
icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/nextcloud.svg
version: stable
links:
    docs: https://docs.nextcloud.com/
    github: https://github.com/nextcloud/docker
    website: https://nextcloud.com/
image: nextcloud:stable
stack: true
services:
    - name: nextcloud
      image: nextcloud:stable
      env:
        MYSQL_DATABASE: nextcloud
        MYSQL_HOST: nextcloud_db
        MYSQL_PASSWORD: ""
        MYSQL_USER: nextcloud
      volumes:
        - nextcloud_data:/var/www/html
    - name: nextcloud_db
      image: mariadb:10.11
      env:
        MYSQL_DATABASE: nextcloud
        MYSQL_PASSWORD: ""
        MYSQL_ROOT_PASSWORD: ""
        MYSQL_USER: nextcloud
      volumes:
        - nextcloud_db_data:/var/lib/mysql
    - name: nextcloud_redis
      image: redis:alpine
