kind: Template
name: onetimesecret
description: Share sensitive information securely with self-destructing links that are only viewable once.
category: security
tags:
    - auth
    - password
    - secret
    - secure
icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/one-time-secret.svg
version: latest
links:
    docs: https://docs.onetimesecret.com
    github: https://github.com/onetimesecret/onetimesecret
    website: https://onetimesecret.com
image: onetimesecret/onetimesecret:latest
stack: true
services:
    - name: onetimesecret
      image: onetimesecret/onetimesecret:latest
      env:
        AUTH_AUTOVERIFY: "true"
        AUTH_SIGNUP: "true"
        COLONEL: ""
        HOST: ""
        RACK_ENV: production
        REDIS_URL: redis://:@onetimesecret-redis:6379/0
        SECRET: ""
        SSL: "true"
    - name: onetimesecret-redis
      image: redis:7-alpine
      command: redis-server --requirepass ${REDIS_PASSWORD}
