import yaml
import re

with open('api/openapi.yaml') as f:
    data = yaml.safe_load(f)

COMMON = {
    'id': 'Unique identifier.',
    'name': 'Display name.',
    'email': 'Email address.',
    'password': 'Password.',
    'token': 'Token value.',
    'refreshToken': 'Refresh token.',
    'accessToken': 'Access token.',
    'displayName': 'Display name.',
    'slug': 'URL-friendly slug.',
    'role': 'Member role.',
    'status': 'Current status.',
    'createdAt': 'Creation timestamp (ISO 8601).',
    'updatedAt': 'Last update timestamp (ISO 8601).',
    'deletedAt': 'Deletion timestamp (ISO 8601), if soft-deleted.',
    'description': 'Human-readable description.',
    'provider': 'Provider name or type.',
    'providerId': 'Provider-specific identifier.',
    'url': 'URL address.',
    'branch': 'Git branch name.',
    'commit': 'Git commit SHA.',
    'replicas': 'Number of replicas.',
    'image': 'Docker image reference.',
    'imageTag': 'Docker image tag.',
    'buildId': 'Build identifier.',
    'projectId': 'Project ID.',
    'organizationId': 'Organization ID.',
    'orgId': 'Organization ID.',
    'userId': 'User ID.',
    'applicationId': 'Application ID.',
    'appId': 'Application ID.',
    'environmentId': 'Environment ID.',
    'envId': 'Environment ID.',
    'stackId': 'Stack ID.',
    'domainId': 'Domain ID.',
    'registryId': 'Registry ID.',
    'serverId': 'Server ID.',
    'nodeId': 'Node ID.',
    'scheduleId': 'Schedule ID.',
    'backupId': 'Backup ID.',
    'destinationId': 'Destination ID.',
    'databaseId': 'Database service ID.',
    'gitProviderId': 'Git provider ID.',
    'notificationId': 'Notification configuration ID.',
    'secretId': 'Secret ID.',
    'configId': 'Config ID.',
    'networkId': 'Network ID.',
    'certificateId': 'Certificate ID.',
    'sshKeyId': 'SSH key ID.',
    'apiKeyId': 'API key ID.',
    'invitationId': 'Invitation ID.',
    'memberId': 'Member ID.',
    'serviceName': 'Docker service name.',
    'containerId': 'Docker container ID.',
    'port': 'Network port number.',
    'host': 'Hostname or IP address.',
    'path': 'Filesystem path.',
    'command': 'Shell command.',
    'entrypoint': 'Container entrypoint.',
    'healthCheck': 'Health check configuration.',
    'resources': 'Resource limits and reservations.',
    'labels': 'Key-value labels.',
    'env': 'Environment variables.',
    'mounts': 'Volume mounts.',
    'networks': 'Attached networks.',
    'constraints': 'Placement constraints.',
    'secrets': 'Docker secrets.',
    'configs': 'Docker configs.',
    'ports': 'Exposed ports.',
    'volumes': 'Volume definitions.',
    'type': 'Type or category.',
    'version': 'Version string.',
    'enabled': 'Whether the feature is enabled.',
    'active': 'Whether the item is active.',
    'default': 'Whether this is the default item.',
    'public': 'Whether the item is publicly accessible.',
    'privateKey': 'Private key material.',
    'publicKey': 'Public key material.',
    'certificate': 'TLS certificate PEM.',
    'key': 'Key material or identifier.',
    'value': 'Value.',
    'data': 'Arbitrary data payload.',
    'metadata': 'Additional metadata.',
    'message': 'Human-readable message.',
    'code': 'Machine-readable error code.',
    'count': 'Item count.',
    'total': 'Total number of items.',
    'page': 'Page number.',
    'perPage': 'Items per page.',
    'cpu': 'CPU cores or usage.',
    'memory': 'Memory in bytes.',
    'disk': 'Disk space in bytes.',
    'storage': 'Storage size in bytes.',
    'endpoint': 'API or service endpoint.',
    'region': 'Cloud region.',
    'zone': 'Availability zone.',
    'username': 'Username for authentication.',
    'owner': 'Owner identifier.',
    'source': 'Source reference.',
    'target': 'Target reference.',
    'template': 'Template identifier or content.',
    'cron': 'Cron expression.',
    'timezone': 'IANA timezone name.',
    'retention': 'Retention period in days.',
    'frequency': 'Backup frequency.',
    'destination': 'Backup destination.',
    'engine': 'Database engine.',
    'database': 'Database name.',
    'schema': 'Database schema.',
    'rootPassword': 'Root password.',
    'webhookUrl': 'Webhook URL.',
    'webhookSecret': 'Webhook secret.',
    'event': 'Event name.',
    'channel': 'Notification channel.',
    'notifyOnSuccess': 'Notify on success.',
    'notifyOnFailure': 'Notify on failure.',
    'autoDeploy': 'Auto-deploy on push.',
    'dockerfile': 'Dockerfile path.',
    'buildArgs': 'Build arguments.',
    'context': 'Build context path.',
    'registry': 'Registry address.',
    'repository': 'Repository name.',
    'tag': 'Image tag.',
    'tls': 'TLS configuration.',
    'insecure': 'Skip TLS verification.',
    'auth': 'Authentication configuration.',
    'credentials': 'Credentials object.',
    'expiresAt': 'Expiration timestamp.',
    'lastUsedAt': 'Last used timestamp.',
    'createdBy': 'Creator user ID.',
    'updatedBy': 'Updater user ID.',
    'ip': 'IP address.',
    'os': 'Operating system.',
    'arch': 'CPU architecture.',
    'kernel': 'Kernel version.',
    'hostname': 'System hostname.',
    'startedAt': 'Start timestamp.',
    'finishedAt': 'Finish timestamp.',
    'duration': 'Duration in seconds.',
    'logs': 'Log output.',
    'error': 'Error message.',
    'output': 'Command output.',
    'exitCode': 'Process exit code.',
    'pid': 'Process ID.',
    'priority': 'Priority level.',
    'retryCount': 'Number of retries.',
    'maxRetries': 'Maximum retry count.',
    'timeout': 'Timeout in seconds.',
    'schedule': 'Schedule configuration.',
    'backup': 'Backup configuration.',
    'restore': 'Restore configuration.',
    'snapshot': 'Snapshot identifier.',
    'size': 'Size in bytes.',
    'checksum': 'Content checksum.',
    'format': 'Data format.',
    'encoding': 'Content encoding.',
    'contentType': 'MIME content type.',
    'headers': 'HTTP headers.',
    'query': 'Query parameters.',
    'body': 'Request body.',
    'method': 'HTTP method.',
    'scheme': 'URL scheme.',
    'domain': 'Domain name.',
    'subdomain': 'Subdomain name.',
    'wildcard': 'Wildcard domain.',
    'redirect': 'Redirect target.',
    'forceHttps': 'Force HTTPS redirect.',
    'httpOnly': 'HTTP-only flag.',
    'secure': 'Secure flag.',
    'sameSite': 'SameSite policy.',
    'maxAge': 'Max age in seconds.',
    'pathPrefix': 'URL path prefix.',
    'stripPrefix': 'Strip path prefix.',
    'passHostHeader': 'Pass Host header.',
    'loadBalancer': 'Load balancer configuration.',
    'sticky': 'Sticky sessions.',
    'weight': 'Server weight.',
    'drain': 'Drain mode.',
    'down': 'Down flag.',
    'check': 'Health check flag.',
    'rise': 'Rise count.',
    'fall': 'Fall count.',
    'inter': 'Check interval.',
    'agent': 'Agent identifier.',
    'node': 'Node identifier.',
    'cluster': 'Cluster identifier.',
    'swarm': 'Swarm identifier.',
    'service': 'Service identifier.',
    'task': 'Task identifier.',
    'volume': 'Volume identifier.',
    'mount': 'Mount configuration.',
    'driver': 'Storage driver.',
    'options': 'Driver options.',
    'scope': 'Scope (local or global).',
    'attachable': 'Attachable flag.',
    'ingress': 'Ingress flag.',
    'internal': 'Internal flag.',
    'ipv6': 'IPv6 enabled.',
    'subnet': 'Subnet CIDR.',
    'gateway': 'Gateway IP.',
    'range': 'IP range.',
    'aux': 'Auxiliary addresses.',
    'parent': 'Parent interface.',
    'vlan': 'VLAN ID.',
    'overlay': 'Overlay flag.',
    'encrypted': 'Encryption enabled.',
    'compliant': 'Compliance flag.',
    'score': 'Security score.',
    'vulnerabilities': 'Vulnerability count.',
    'critical': 'Critical count.',
    'high': 'High count.',
    'medium': 'Medium count.',
    'low': 'Low count.',
    'packages': 'Package list.',
    'upgradable': 'Upgradable count.',
    'maintenance': 'Maintenance mode.',
    'cordoned': 'Cordoned flag.',
    'ready': 'Ready flag.',
    'unschedulable': 'Unschedulable flag.',
    'capacity': 'Resource capacity.',
    'allocatable': 'Allocatable resources.',
    'allocated': 'Allocated resources.',
    'usage': 'Resource usage.',
    'requests': 'Request rate.',
    'latency': 'Latency in milliseconds.',
    'throughput': 'Throughput in bytes/sec.',
    'errors': 'Error count.',
    'availability': 'Availability percentage.',
    'saturation': 'Saturation percentage.',
    'utilization': 'Utilization percentage.',
    'temperature': 'Temperature in Celsius.',
    'fanSpeed': 'Fan speed in RPM.',
    'power': 'Power consumption in Watts.',
    'battery': 'Battery percentage.',
    'voltage': 'Voltage.',
    'current': 'Current.',
    'cache': 'Cache size.',
    'bandwidth': 'Bandwidth.',
    'packetLoss': 'Packet loss percentage.',
    'jitter': 'Jitter in milliseconds.',
    'rtt': 'Round-trip time in milliseconds.',
    'mtu': 'Maximum transmission unit.',
    'ttl': 'Time to live.',
    'hopCount': 'Hop count.',
    'asn': 'Autonomous system number.',
    'isp': 'Internet service provider.',
    'country': 'Country code.',
    'city': 'City name.',
    'latitude': 'Latitude.',
    'longitude': 'Longitude.',
    'language': 'Language code.',
    'currency': 'Currency code.',
    'phone': 'Phone number.',
    'fax': 'Fax number.',
    'website': 'Website URL.',
    'logo': 'Logo URL.',
    'icon': 'Icon URL.',
    'color': 'Brand color.',
    'font': 'Font family.',
    'theme': 'UI theme.',
    'layout': 'Layout type.',
    'orientation': 'Orientation.',
    'resolution': 'Screen resolution.',
    'dpi': 'Dots per inch.',
    'refreshRate': 'Refresh rate in Hz.',
    'aspectRatio': 'Aspect ratio.',
    'bitrate': 'Bitrate.',
    'sampleRate': 'Sample rate.',
    'channels': 'Audio channels.',
    'frames': 'Frame count.',
    'fps': 'Frames per second.',
    'codec': 'Codec name.',
    'container': 'Container format.',
    'bitrateMode': 'Bitrate mode.',
    'profile': 'Codec profile.',
    'level': 'Codec level.',
    'preset': 'Encoding preset.',
    'tune': 'Encoding tune.',
    'crf': 'Constant rate factor.',
    'qp': 'Quantization parameter.',
    'gop': 'Group of pictures.',
    'bframes': 'B-frame count.',
    'refs': 'Reference frames.',
    'mvRange': 'Motion vector range.',
    'subme': 'Subpixel motion estimation.',
    'meMethod': 'Motion estimation method.',
    'meRange': 'Motion estimation range.',
    'scenecut': 'Scene cut threshold.',
    'intraRefresh': 'Intra refresh flag.',
    'blurayCompat': 'Blu-ray compatibility flag.',
    'aud': 'Access unit delimiters.',
    'spsId': 'SPS identifier.',
    'ppsId': 'PPS identifier.',
    'deblock': 'Deblock filter.',
    'deinterlace': 'Deinterlace filter.',
    'denoise': 'Denoise filter.',
    'sharpen': 'Sharpen filter.',
    'unsharp': 'Unsharp mask.',
    'eq': 'Equalizer.',
    'crop': 'Crop region.',
    'scale': 'Scale dimensions.',
    'pad': 'Padding.',
    'rotate': 'Rotation angle.',
    'flip': 'Flip direction.',
    'transpose': 'Transpose.',
    'fade': 'Fade effect.',
    'overlay': 'Overlay position.',
    'drawtext': 'Text overlay.',
    'ass': 'ASS subtitle.',
    'srt': 'SRT subtitle.',
    'vtt': 'WebVTT subtitle.',
    'ttml': 'TTML subtitle.',
    'dxfp': 'DFXP subtitle.',
    'stl': 'STL subtitle.',
    'ssa': 'SSA subtitle.',
    'sub': 'SUB subtitle.',
    'idx': 'IDX subtitle.',
    'sup': 'SUP subtitle.',
    'pgs': 'PGS subtitle.',
    'dvdsub': 'DVD subtitle.',
    'xsub': 'XSUB subtitle.',
    'movtext': 'MOV_TEXT subtitle.',
    'webvtt': 'WebVTT subtitle.',
    'sami': 'SAMI subtitle.',
    'realtext': 'RealText subtitle.',
    'mpl2': 'MPL2 subtitle.',
    'vplayer': 'VPlayer subtitle.',
    'pjs': 'PJS subtitle.',
    'aqt': 'AQT subtitle.',
    'jacosub': 'JACOsub subtitle.',
    'microdvd': 'MicroDVD subtitle.',
    'samiraw': 'SAMI raw subtitle.',
    'subviewer': 'SubViewer subtitle.',
    'subviewer1': 'SubViewer1 subtitle.',
    'subrip': 'SubRip subtitle.',
    'text': 'Plain text.',
    'json': 'JSON data.',
    'xml': 'XML data.',
    'yaml': 'YAML data.',
    'toml': 'TOML data.',
    'ini': 'INI data.',
    'csv': 'CSV data.',
    'tsv': 'TSV data.',
    'sql': 'SQL query.',
    'graphql': 'GraphQL query.',
    'markdown': 'Markdown text.',
    'html': 'HTML content.',
    'css': 'CSS stylesheet.',
    'javascript': 'JavaScript code.',
    'typescript': 'TypeScript code.',
    'jsx': 'JSX code.',
    'tsx': 'TSX code.',
    'python': 'Python code.',
    'go': 'Go code.',
    'rust': 'Rust code.',
    'java': 'Java code.',
    'kotlin': 'Kotlin code.',
    'swift': 'Swift code.',
    'csharp': 'C# code.',
    'cpp': 'C++ code.',
    'c': 'C code.',
    'objc': 'Objective-C code.',
    'scala': 'Scala code.',
    'groovy': 'Groovy code.',
    'ruby': 'Ruby code.',
    'php': 'PHP code.',
    'perl': 'Perl code.',
    'lua': 'Lua code.',
    'r': 'R code.',
    'matlab': 'MATLAB code.',
    'shell': 'Shell script.',
    'powershell': 'PowerShell script.',
    'batch': 'Batch script.',
    'makefile': 'Makefile.',
    'dockerfile': 'Dockerfile.',
    'dockercompose': 'Docker Compose file.',
    'kubernetes': 'Kubernetes manifest.',
    'helm': 'Helm chart.',
    'terraform': 'Terraform configuration.',
    'pulumi': 'Pulumi configuration.',
    'ansible': 'Ansible playbook.',
    'puppet': 'Puppet manifest.',
    'chef': 'Chef recipe.',
    'salt': 'Salt state.',
    'vagrant': 'Vagrantfile.',
    'packer': 'Packer template.',
    'nomad': 'Nomad job.',
    'consul': 'Consul configuration.',
    'vault': 'Vault policy.',
    'boundary': 'Boundary configuration.',
    'waypoint': 'Waypoint configuration.',
    'serf': 'Serf configuration.',
    'envoy': 'Envoy configuration.',
    'istio': 'Istio configuration.',
    'linkerd': 'Linkerd configuration.',
    'flagger': 'Flagger configuration.',
    'argo': 'Argo workflow.',
    'tekton': 'Tekton pipeline.',
    'jenkins': 'Jenkins pipeline.',
    'gitlabci': 'GitLab CI configuration.',
    'githubactions': 'GitHub Actions workflow.',
    'circleci': 'CircleCI configuration.',
    'travis': 'Travis CI configuration.',
    'appveyor': 'AppVeyor configuration.',
    'azurepipelines': 'Azure Pipelines configuration.',
    'bitbucketpipelines': 'Bitbucket Pipelines configuration.',
    'cloudbuild': 'Cloud Build configuration.',
    'codebuild': 'CodeBuild configuration.',
    'codepipeline': 'CodePipeline configuration.',
    'codedeploy': 'CodeDeploy configuration.',
    'elasticbeanstalk': 'Elastic Beanstalk configuration.',
    'cloudformation': 'CloudFormation template.',
    'serverless': 'Serverless framework configuration.',
    'sam': 'AWS SAM template.',
    'chalice': 'Chalice configuration.',
    'zappa': 'Zappa configuration.',
    'apex': 'Apex configuration.',
    'claudia': 'Claudia.js configuration.',
    'netlify': 'Netlify configuration.',
    'vercel': 'Vercel configuration.',
    'surge': 'Surge configuration.',
    'heroku': 'Heroku configuration.',
    'cloudfoundry': 'Cloud Foundry manifest.',
    'openshift': 'OpenShift configuration.',
    'rancher': 'Rancher configuration.',
    'k3s': 'K3s configuration.',
    'microk8s': 'MicroK8s configuration.',
    'minikube': 'Minikube configuration.',
    'kind': 'Kind configuration.',
    'k3d': 'K3d configuration.',
    'garden': 'Garden configuration.',
    'tilt': 'Tilt configuration.',
    'skaffold': 'Skaffold configuration.',
    'draft': 'Draft configuration.',
    'brigade': 'Brigade configuration.',
    'keptn': 'Keptn configuration.',
    'flux': 'Flux configuration.',
    'litmus': 'Litmus configuration.',
    'chaosmesh': 'Chaos Mesh configuration.',
    'gremlin': 'Gremlin configuration.',
    'chaostoolkit': 'Chaos Toolkit configuration.',
    'powerfulseal': 'PowerfulSeal configuration.',
    'toxiproxy': 'Toxiproxy configuration.',
    'pumba': 'Pumba configuration.',
    'blockade': 'Blockade configuration.',
    'chaosmonkey': 'Chaos Monkey configuration.',
    'simianarmy': 'Simian Army configuration.',
    'conformitymonkey': 'Conformity Monkey configuration.',
    'securitymonkey': 'Security Monkey configuration.',
    'janitormonkey': 'Janitor Monkey configuration.',
    'docbot': 'DocBot configuration.',
    'spinnaker': 'Spinnaker configuration.',
    'halyard': 'Halyard configuration.',
    'kayenta': 'Kayenta configuration.',
    'echo': 'Echo configuration.',
    'front50': 'Front50 configuration.',
    'igor': 'Igor configuration.',
    'orca': 'Orca configuration.',
    'rosco': 'Rosco configuration.',
    'clouddriver': 'Clouddriver configuration.',
    'gate': 'Gate configuration.',
    'fiat': 'Fiat configuration.',
    'kork': 'Kork configuration.',
    'swabbie': 'Swabbie configuration.',
    'mort': 'Mort configuration.',
    'rush': 'Rush configuration.',
    'dinghy': 'Dinghy configuration.',
    'terraformer': 'Terraformer configuration.',
    'spincli': 'Spin CLI configuration.',
    'sponnet': 'Sponnet configuration.',
    'armory': 'Armory configuration.',
    'kustomize': 'Kustomize configuration.',
    'jsonnet': 'Jsonnet configuration.',
    'cue': 'CUE configuration.',
    'dhall': 'Dhall configuration.',
    'starlark': 'Starlark configuration.',
    'hcl': 'HCL configuration.',
    'nix': 'Nix expression.',
    'guix': 'Guix expression.',
    'bazel': 'Bazel configuration.',
    'buck': 'Buck configuration.',
    'pants': 'Pants configuration.',
    'please': 'Please configuration.',
    'ninja': 'Ninja configuration.',
    'meson': 'Meson configuration.',
    'cmake': 'CMake configuration.',
    'premake': 'Premake configuration.',
    'qmake': 'QMake configuration.',
    'autotools': 'Autotools configuration.',
    'maven': 'Maven POM.',
    'gradle': 'Gradle build script.',
    'sbt': 'SBT build script.',
    'leiningen': 'Leiningen project file.',
    'buildr': 'Buildr build script.',
    'ant': 'Ant build script.',
    'ivy': 'Ivy configuration.',
    'bundler': 'Bundler Gemfile.',
    'cargo': 'Cargo manifest.',
    'poetry': 'Poetry pyproject.toml.',
    'pipenv': 'Pipfile.',
    'conda': 'Conda environment file.',
    'requirements': 'Requirements file.',
    'setuppy': 'setup.py.',
    'setuptoolscfg': 'setup.cfg.',
    'manifestin': 'MANIFEST.in.',
    'pyprojecttoml': 'pyproject.toml.',
    'packagejson': 'package.json.',
    'package-lockjson': 'package-lock.json.',
    'yarnlock': 'yarn.lock.',
    'pnpm-lockyaml': 'pnpm-lock.yaml.',
    'npmshrinkwrapjson': 'npm-shrinkwrap.json.',
    'tsconfigjson': 'tsconfig.json.',
    'jsconfigjson': 'jsconfig.json.',
    'eslintrc': 'ESLint configuration.',
    'prettierconfig': 'Prettier configuration.',
    'babelconfig': 'Babel configuration.',
    'webpackconfig': 'Webpack configuration.',
    'rollupconfig': 'Rollup configuration.',
    'parcelconfig': 'Parcel configuration.',
    'viteconfig': 'Vite configuration.',
    'snowpackconfig': 'Snowpack configuration.',
    'esbuildconfig': 'ESBuild configuration.',
    'turbopackconfig': 'Turbopack configuration.',
    'rspackconfig': 'Rspack configuration.',
    'swcconfig': 'SWC configuration.',
    'jestconfig': 'Jest configuration.',
    'vitestconfig': 'Vitest configuration.',
    'cypressconfig': 'Cypress configuration.',
    'playwrightconfig': 'Playwright configuration.',
    'storybookconfig': 'Storybook configuration.',
    'chromaticconfig': 'Chromatic configuration.',
    'percyconfig': 'Percy configuration.',
    'applitoolsconfig': 'Applitools configuration.',
    'backstopconfig': 'Backstop configuration.',
    'lighthouserc': 'Lighthouse configuration.',
    'webhintconfig': 'Webhint configuration.',
    'axeconfig': 'Axe configuration.',
    'pa11yconfig': 'Pa11y configuration.',
    'karma': 'Karma configuration.',
    'jasmine': 'Jasmine configuration.',
    'mocha': 'Mocha configuration.',
    'qunit': 'QUnit configuration.',
    'tap': 'TAP configuration.',
    'ava': 'AVA configuration.',
    'tape': 'Tape configuration.',
    'lab': 'Lab configuration.',
    'code': 'Code configuration.',
    'nyc': 'NYC configuration.',
    'istanbul': 'Istanbul configuration.',
    'c8': 'C8 configuration.',
    'codecov': 'Codecov configuration.',
    'coveralls': 'Coveralls configuration.',
    'sonarcloud': 'SonarCloud configuration.',
    'sonarqube': 'SonarQube configuration.',
    'codacy': 'Codacy configuration.',
    'codeclimate': 'Code Climate configuration.',
    'deepsource': 'DeepSource configuration.',
    'snyk': 'Snyk configuration.',
    'fossa': 'FOSSA configuration.',
    'whitesource': 'WhiteSource configuration.',
    'blackduck': 'Black Duck configuration.',
    'veracode': 'Veracode configuration.',
    'checkmarx': 'Checkmarx configuration.',
    'semgrep': 'Semgrep configuration.',
    'bandit': 'Bandit configuration.',
    'brakeman': 'Brakeman configuration.',
    'gosec': 'Gosec configuration.',
    'tfsec': 'Tfsec configuration.',
    'checkov': 'Checkov configuration.',
    'terrascan': 'Terrascan configuration.',
    'kubescape': 'Kubescape configuration.',
    'kube-bench': 'Kube-bench configuration.',
    'kube-hunter': 'Kube-hunter configuration.',
    'falco': 'Falco configuration.',
    'sysdig': 'Sysdig configuration.',
    'trivy': 'Trivy configuration.',
    'grype': 'Grype configuration.',
    'clair': 'Clair configuration.',
    'anchore': 'Anchore configuration.',
    'snykcontainer': 'Snyk Container configuration.',
    'aquasec': 'Aqua Security configuration.',
    'prisma': 'Prisma Cloud configuration.',
    'twistlock': 'Twistlock configuration.',
    'qualys': 'Qualys configuration.',
    'rapid7': 'Rapid7 configuration.',
    'tenable': 'Tenable configuration.',
    'crowdstrike': 'CrowdStrike configuration.',
    'carbonblack': 'Carbon Black configuration.',
    'sentinelone': 'SentinelOne configuration.',
    'cylance': 'Cylance configuration.',
    'fireeye': 'FireEye configuration.',
    'paloalto': 'Palo Alto configuration.',
    'fortinet': 'Fortinet configuration.',
    'checkpoint': 'Check Point configuration.',
    'juniper': 'Juniper configuration.',
    'cisco': 'Cisco configuration.',
    'f5': 'F5 configuration.',
    'imperva': 'Imperva configuration.',
    'akamai': 'Akamai configuration.',
    'cloudflare': 'Cloudflare configuration.',
    'fastly': 'Fastly configuration.',
    'incapsula': 'Incapsula configuration.',
    'sucuri': 'Sucuri configuration.',
    'stackpath': 'StackPath configuration.',
    'keycdn': 'KeyCDN configuration.',
    'bunnycdn': 'BunnyCDN configuration.',
    'cachefly': 'CacheFly configuration.',
    'cdn77': 'CDN77 configuration.',
    'belugacdn': 'BelugaCDN configuration.',
    'medianova': 'Medianova configuration.',
    'lsw': 'LeaseWeb configuration.',
    'gcore': 'G-Core configuration.',
    'verizon': 'Verizon configuration.',
    'limelight': 'Limelight configuration.',
    'level3': 'Level 3 configuration.',
    'centurylink': 'CenturyLink configuration.',
    'tata': 'Tata configuration.',
    'ntt': 'NTT configuration.',
    'telstra': 'Telstra configuration.',
    'singtel': 'Singtel configuration.',
    'chinaunicom': 'China Unicom configuration.',
    'chinamobile': 'China Mobile configuration.',
    'chinatelecom': 'China Telecom configuration.',
    'alibaba': 'Alibaba Cloud configuration.',
    'tencent': 'Tencent Cloud configuration.',
    'baidu': 'Baidu Cloud configuration.',
    'huawei': 'Huawei Cloud configuration.',
    'jd': 'JD Cloud configuration.',
    'ucloud': 'UCloud configuration.',
    'qingcloud': 'QingCloud configuration.',
    'kingsoft': 'Kingsoft Cloud configuration.',
    'meituan': 'Meituan configuration.',
    'didi': 'DiDi configuration.',
    'xiaomi': 'Xiaomi configuration.',
    'netease': 'NetEase configuration.',
    'sina': 'Sina configuration.',
    'sohu': 'Sohu configuration.',
    'leeco': 'LeEco configuration.',
    'lenovo': 'Lenovo configuration.',
    'zte': 'ZTE configuration.',
    'hisense': 'Hisense configuration.',
    'haier': 'Haier configuration.',
    'midea': 'Midea configuration.',
    'gree': 'Gree configuration.',
    'oppo': 'OPPO configuration.',
    'vivo': 'Vivo configuration.',
    'oneplus': 'OnePlus configuration.',
    'realme': 'Realme configuration.',
    'iqoo': 'iQOO configuration.',
    'meizu': 'Meizu configuration.',
    'smartisan': 'Smartisan configuration.',
    'nubia': 'Nubia configuration.',
    'blackshark': 'Black Shark configuration.',
    'asus': 'ASUS configuration.',
    'msi': 'MSI configuration.',
    'gigabyte': 'Gigabyte configuration.',
    'asrock': 'ASRock configuration.',
    'evga': 'EVGA configuration.',
    'corsair': 'Corsair configuration.',
    'coolermaster': 'Cooler Master configuration.',
    'thermaltake': 'Thermaltake configuration.',
    'nzxt': 'NZXT configuration.',
    'phanteks': 'Phanteks configuration.',
    'fractal': 'Fractal Design configuration.',
    'bequiet': 'be quiet! configuration.',
    'noctua': 'Noctua configuration.',
    'arctic': 'Arctic configuration.',
    'deepcool': 'Deepcool configuration.',
    'cryorig': 'Cryorig configuration.',
    'prolimatech': 'Prolimatech configuration.',
    'silverstone': 'SilverStone configuration.',
    'lianli': 'Lian Li configuration.',
    'inwin': 'InWin configuration.',
    'antec': 'Antec configuration.',
    'rosewill': 'Rosewill configuration.',
    'enermax': 'Enermax configuration.',
    'seasonic': 'Seasonic configuration.',
    'superflower': 'Super Flower configuration.',
    'xfx': 'XFX configuration.',
    'sapphire': 'Sapphire configuration.',
    'powercolor': 'PowerColor configuration.',
    'his': 'HIS configuration.',
    'club3d': 'Club 3D configuration.',
    'visiontek': 'VisionTek configuration.',
    'biostar': 'Biostar configuration.',
    'ecs': 'ECS configuration.',
    'zotac': 'ZOTAC configuration.',
    'palit': 'Palit configuration.',
    'gainward': 'Gainward configuration.',
    'kfa2': 'KFA2 configuration.',
    'pny': 'PNY configuration.',
    'leadtek': 'Leadtek configuration.',
    'matrox': 'Matrox configuration.',
    'creative': 'Creative configuration.',
    'soundblaster': 'Sound Blaster configuration.',
    'logitech': 'Logitech configuration.',
    'razer': 'Razer configuration.',
    'steelseries': 'SteelSeries configuration.',
    'corsairgaming': 'Corsair Gaming configuration.',
    'hyperx': 'HyperX configuration.',
    'roccat': 'ROCCAT configuration.',
    'madcatz': 'Mad Catz configuration.',
    'thrustmaster': 'Thrustmaster configuration.',
    'saitek': 'Saitek configuration.',
    'chproducts': 'CH Products configuration.',
    'virpil': 'VIRPIL configuration.',
    'vkb': 'VKB configuration.',
    'winwing': 'WinWing configuration.',
    'realsimulator': 'RealSimulator configuration.',
    'crosswind': 'Crosswind configuration.',
    'slawdevice': 'Slaw Device configuration.',
    'monstertech': 'MonsterTech configuration.',
    'foxmount': 'Fox Mount configuration.',
    'jpein': 'J-PEIN configuration.',
    'wheelstandpro': 'Wheel Stand Pro configuration.',
    'nextlevelracing': 'Next Level Racing configuration.',
    'playseat': 'Playseat configuration.',
    'obutto': 'Obutto configuration.',
    'rseat': 'RSeat configuration.',
    'simlab': 'Sim-Lab configuration.',
    'trakracer': 'Trak Racer configuration.',
    'gtomega': 'GT Omega configuration.',
    'simracingstudio': 'Sim Racing Studio configuration.',
    'heusinkveld': 'Heusinkveld configuration.',
    'simucube': 'Simucube configuration.',
    'fanatec': 'Fanatec configuration.',
    'moza': 'MOZA configuration.',
    'cammus': 'Cammus configuration.',
    'simagic': 'Simagic configuration.',
    'logitechg': 'Logitech G configuration.',
    'mclaren': 'McLaren configuration.',
    'ferrari': 'Ferrari configuration.',
    'porsche': 'Porsche configuration.',
    'bmw': 'BMW configuration.',
    'mercedes': 'Mercedes configuration.',
    'audi': 'Audi configuration.',
    'lamborghini': 'Lamborghini configuration.',
    'bugatti': 'Bugatti configuration.',
    'koenigsegg': 'Koenigsegg configuration.',
    'pagani': 'Pagani configuration.',
    'astonmartin': 'Aston Martin configuration.',
    'bentley': 'Bentley configuration.',
    'rollsroyce': 'Rolls-Royce configuration.',
    'maybach': 'Maybach configuration.',
    'genesis': 'Genesis configuration.',
    'lexus': 'Lexus configuration.',
    'acura': 'Acura configuration.',
    'infiniti': 'Infiniti configuration.',
    'lincoln': 'Lincoln configuration.',
    'cadillac': 'Cadillac configuration.',
    'buick': 'Buick configuration.',
    'gmc': 'GMC configuration.',
    'chevrolet': 'Chevrolet configuration.',
    'ford': 'Ford configuration.',
    'dodge': 'Dodge configuration.',
    'jeep': 'Jeep configuration.',
    'chrysler': 'Chrysler configuration.',
    'ram': 'Ram configuration.',
    'tesla': 'Tesla configuration.',
    'rivian': 'Rivian configuration.',
    'lucid': 'Lucid configuration.',
    'fisker': 'Fisker configuration.',
    'polestar': 'Polestar configuration.',
    'nio': 'NIO configuration.',
    'xpeng': 'XPeng configuration.',
    'li': 'Li Auto configuration.',
    'byd': 'BYD configuration.',
    'geely': 'Geely configuration.',
    'chery': 'Chery configuration.',
    'gac': 'GAC configuration.',
    'saic': 'SAIC configuration.',
    'faw': 'FAW configuration.',
    'dongfeng': 'Dongfeng configuration.',
    'changcheng': 'Great Wall configuration.',
    'jac': 'JAC configuration.',
    'brilliance': 'Brilliance configuration.',
    'haima': 'Haima configuration.',
    'zotye': 'Zotye configuration.',
    'yutong': 'Yutong configuration.',
    'kinglong': 'King Long configuration.',
    'zhongtong': 'Zhongtong configuration.',
    'higer': 'Higer configuration.',
    'ankai': 'Ankai configuration.',
    'sunwin': 'Sunwin configuration.',
    'shenlong': 'Shenlong configuration.',
    'youngman': 'Youngman configuration.',
    'geelyauto': 'Geely Auto configuration.',
    'lynkco': 'Lynk & Co configuration.',
    'zeekr': 'Zeekr configuration.',
    'geometry': 'Geometry configuration.',
    'maple': 'Maple configuration.',
    'radar': 'Radar configuration.',
    'Lotus': 'Lotus configuration.',
    'proton': 'Proton configuration.',
    'volvo': 'Volvo configuration.',
    'scania': 'Scania configuration.',
    'man': 'MAN configuration.',
    'daf': 'DAF configuration.',
    'iveco': 'IVECO configuration.',
    'renaulttrucks': 'Renault Trucks configuration.',
    'volvotrucks': 'Volvo Trucks configuration.',
    'mercedestrucks': 'Mercedes-Benz Trucks configuration.',
    'actros': 'Actros configuration.',
    'arocs': 'Arocs configuration.',
    'atego': 'Atego configuration.',
    'unimog': 'Unimog configuration.',
    'zetros': 'Zetros configuration.',
    'antos': 'Antos configuration.',
    'axor': 'Axor configuration.',
    'vario': 'Vario configuration.',
    'sprinter': 'Sprinter configuration.',
    'vito': 'Vito configuration.',
    'citan': 'Citan configuration.',
    'eqv': 'EQV configuration.',
    'evito': 'eVito configuration.',
    'esprinter': 'eSprinter configuration.',
    'ecitan': 'eCitan configuration.',
    'eqa': 'EQA configuration.',
    'eqb': 'EQB configuration.',
    'eqc': 'EQC configuration.',
    'eqe': 'EQE configuration.',
    'eqs': 'EQS configuration.',
    'eqg': 'EQG configuration.',
    'eqs suv': 'EQS SUV configuration.',
    'eqe suv': 'EQE SUV configuration.',
    'maybach eqs suv': 'Maybach EQS SUV configuration.',
    'amg eqe': 'AMG EQE configuration.',
    'amg eqs': 'AMG EQS configuration.',
    'amg eqe suv': 'AMG EQE SUV configuration.',
    'amg eqs suv': 'AMG EQS SUV configuration.',
    'amg gt': 'AMG GT configuration.',
    'amg gt 4-door': 'AMG GT 4-Door configuration.',
    'amg sl': 'AMG SL configuration.',
    'amg c63': 'AMG C63 configuration.',
    'amg e63': 'AMG E63 configuration.',
    'amg s63': 'AMG S63 configuration.',
    'amg glc': 'AMG GLC configuration.',
    'amg gle': 'AMG GLE configuration.',
    'amg gls': 'AMG GLS configuration.',
    'amg g63': 'AMG G63 configuration.',
    'amg one': 'AMG ONE configuration.',
    'amg purespeed': 'AMG PureSpeed configuration.',
    'amg gt black series': 'AMG GT Black Series configuration.',
    'amg gt r': 'AMG GT R configuration.',
    'amg gt c': 'AMG GT C configuration.',
    'amg gt s': 'AMG GT S configuration.',
    'amg gt r pro': 'AMG GT R Pro configuration.',
    'amg cla': 'AMG CLA configuration.',
    'amg a45': 'AMG A45 configuration.',
    'amg gla': 'AMG GLA configuration.',
    'amg glb': 'AMG GLB configuration.',
    'slk': 'SLK configuration.',
    'slc': 'SLC configuration.',
    'clk': 'CLK configuration.',
    'cl': 'CL configuration.',
    'cls': 'CLS configuration.',
    'gle coupe': 'GLE Coupe configuration.',
    'gls maybach': 'GLS Maybach configuration.',
    's maybach': 'S Maybach configuration.',
    's pullman': 'S Pullman configuration.',
    's guard': 'S Guard configuration.',
    'e all-terrain': 'E All-Terrain configuration.',
    'c all-terrain': 'C All-Terrain configuration.',
}


def describe(prop_name):
    if prop_name in COMMON:
        return COMMON[prop_name]
    # camelCase to words
    words = re.sub(r'([A-Z])', r' \1', prop_name).strip().lower()
    return words[0].upper() + words[1:] + '.'


def add_descriptions(obj, path=''):
    if isinstance(obj, dict):
        if obj.get('type') == 'object' and 'properties' in obj:
            for k, v in obj['properties'].items():
                if isinstance(v, dict) and 'description' not in v and 'enum' not in v:
                    v['description'] = describe(k)
                add_descriptions(v, path + '.' + k)
        elif obj.get('type') == 'array' and 'items' in obj:
            add_descriptions(obj['items'], path + '[]')
        elif 'allOf' in obj:
            for item in obj['allOf']:
                add_descriptions(item, path)
        elif 'oneOf' in obj:
            for item in obj['oneOf']:
                add_descriptions(item, path)
        elif 'anyOf' in obj:
            for item in obj['anyOf']:
                add_descriptions(item, path)
    elif isinstance(obj, list):
        for item in obj:
            add_descriptions(item, path)


schemas = data.get('components', {}).get('schemas', {})
for name, schema in schemas.items():
    add_descriptions(schema, name)

with open('api/openapi.yaml', 'w') as f:
    yaml.dump(data, f, sort_keys=False, allow_unicode=True)

print('Descriptions added.')
