run:
  timeout: 5m
  go: "1.25"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gocritic
    - revive

linters-settings:
  gosec:
    excludes:
      - G104 # Auditing of errors is handled separately
  revive:
    rules:
      - name: exported
        arguments: ["checkPrivateReceivers", "sayRepetitiveInsteadOfStutters"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 10
